language: ruby
# See https://docs.travis-ci.com/user/database-setup/#PostgreSQL
services:
- postgresql
addons:
  postgresql: '9.6'
# Cache bundle between builds
# See https://docs.travis-ci.com/user/caching/
cache: bundler
jobs:
  include:
  - stage: test
    before_script:
    - bin/rails db:setup
    script:
    - bundle exec rspec
  - script: bundle exec rubocop
  - stage: deploy
    cache: skip
    install: skip
    before_script: skip
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: lVZxGuy5uNaR4OdFfV3uu7bEqlN2RwC9UzeYEh/712UPM0AOXYRW+3UdjTn3Zr2e11bE1h7K2OcqJp7WhV25sUD2PPezKkf9lxrmu48UtzlGlkQJH1/fb3jlATV1uCtgxgutzysmcnw9ewtOnSoQltT+rFXQeFR62chqqtkA5qYFWgUxSlEK8Y1Z7uFRTPdBS33R5qDhyuohsI8FM64q4XtmARHsjUuOry8L8Ia89Rue5pbkfl29eRLt3ZAQX2ZVaevqgxWMEaOvKLqN7ZpeM3uQEA8M5G7PbdC3EVe8HvdjsXXVyOD/ljhdSxvW1xt/aV+Q1yHWNmv4FGTdQzPqzUPv1DorLTSusf4zePEGA56zdCNZ56x1wvV8rba01qNbrtrKewtTPcKp/M5bgyGGXSVFNGWnQv08hVOTXQEGWEqB/gcAAn+uCIl1eflySbxKX/LCMWjmCx0tfdKtS23hxuZPsWKKIJhUYWfpP7VWUok0z+XxCbhboSTsspw0VZmXsv6Vm6OpplVu3Sc2O4riVOZnRNLPiPeGszIwbNK0qlUG/G+RiLFuKZoI8RBhYprebIcZu2rd+F/yElhlHWvBQlvL8FQE1FKnjmIxyjY698gs7acC7ste7HxZp3m29+mEvnJcCfAqkFe2960+JVXB2p012g0vvQkznA/HbO6xq04=
      app:
        master: rubytoolbox-production
      run:
      - rake db:migrate
